kintone-labs/kintone-ui-component

docs/Reference/CheckBox.md, docs/Reference/Dropdown.md, docs/Reference/Label.md, docs/Reference/MultipleChoice.md, docs/Reference/RadioButton.md, docs/Reference/Spinner.md
https://kintone.github.io/kintone-ui-component/ has brocken code sample.
Please fix it.
=> Mkdocs - fix broken code sample

src/js/components/Attachment.js
- change the function "_getReactElement" for defining "this._reactObject"
=> v0.2.0_attachment

src/js/components-react/TextArea.js
BUG fix
https://bozuman.cybozu.com/k/24200/show#record=666
=> v 0.2.0 TextArea

README.md
- Add npm package budge
- Add link to npm package page
=> Add npm package budge

src/css/Item.css, src/css/MultipleChoice.css
=>  Apply the background for each option when user hover each option

src/js/TextArea/index.ts, src/react/TextArea/index.tsx
Fix:
- Cannot get current value in textbox when using method getValue()
- Cannot resize in IE
-
=> Fix bug Text area

src/react/DateTime/index.tsx
This reverts commit 934d4c204b5c971d4a0447a4fb127ee432709667.
=> Revert "Revert "update useEffect""

docs/Reference/Alert.md, docs/Reference/CheckBox.md, docs/Reference/Dropdown.md, docs/Reference/FieldGroup.md, docs/Reference/MultipleChoice.md, docs/Reference/RadioButton.md, docs/Reference/Table.md, docs/Reference/Tabs.md
Convert all property of constructor to optional
=> Convert all property of constructor to optional (docs)

src/js/CheckBox/Item.ts, src/js/CheckBox/index.ts, src/js/utils/AbstractMultiSelection.ts, src/react/Attachment/AttachmentFileItem.tsx, src/react/Attachment/index.tsx, src/react/Button/index.tsx, src/react/CheckBox/index.tsx, src/react/Dropdown/index.tsx, src/react/Item/index.tsx, src/react/utils/AbstractMultiSelection.tsx, src/react/utils/AbstractSingleSelection.tsx
=> Sprint 11 ssr 495 huong code

docs/Reference/Alert.md, docs/Reference/Button.md, docs/Reference/CheckBox.md, docs/Reference/ColorPicker.md, docs/Reference/DateTime.md, docs/Reference/Dropdown.md, docs/Reference/IconButton.md, docs/Reference/MultipleChoice.md, docs/Reference/RadioButton.md
=> Sprint 11 mkdocs ssr 495 huong

docs/Reference/RadioButton.md
change option params type is yes and option name is conditional for radio button
=> change option params type is yes and option name is conditional for radio button 

docs/Reference/Alert.md, docs/Reference/Attachment.md, docs/Reference/Button.md, docs/Reference/CheckBox.md, docs/Reference/ColorPicker.md, docs/Reference/DateTime.md, docs/Reference/Dialog.md, docs/Reference/Dropdown.md, docs/Reference/FieldGroup.md, docs/Reference/IconButton.md, docs/Reference/Label.md, docs/Reference/MultipleChoice.md, docs/Reference/NotifyPopup.md, docs/Reference/RadioButton.md, docs/Reference/Spinner.md, docs/Reference/Tabs.md, docs/Reference/Text.md
- Change default value bold-> normal
=> Add React render to simple code and change default value(visible,disable) text bold -> text normal

.babelrc, package.json, src/js/index.ts, webpack.config.js
Reverts kintone/kintone-ui-component#290
=> Revert "use built in"

src/react/Text/index.tsx, src/react/TextArea/index.tsx
I want to support  `placeholder` attribute in Text, TextArea component.
=> Support placeholder attribute

jest.config.js, package-lock.json, package.json, src/js/MultipleChoice/__test__/addItem.test.ts, src/js/MultipleChoice/__test__/disable.test.ts, src/js/MultipleChoice/__test__/disableItem.test.ts, src/js/MultipleChoice/__test__/enable.test.ts, src/js/MultipleChoice/__test__/enableItem.test.ts, src/js/MultipleChoice/__test__/getItem.test.ts, src/js/MultipleChoice/__test__/hide.test.ts, src/js/MultipleChoice/__test__/onEvent.test.ts, src/js/MultipleChoice/__test__/removeItem.test.ts, src/js/MultipleChoice/__test__/render.test.ts, src/js/MultipleChoice/__test__/setAndGetItems.test.ts, src/js/MultipleChoice/__test__/setAndGetValue.test.ts, src/js/MultipleChoice/__test__/show.test.ts, src/react/MultipleChoice/__test__/render.test.tsx
@youtr-s 
Please review the unit test code for MultipleChoice.
=> KUC unit test for MultipleChoice

src/constant/Message.ts, src/js/MultipleChoice/__test__/addItem.test.ts, src/js/MultipleChoice/__test__/onEvent.test.ts, src/js/MultipleChoice/__test__/render.test.ts, src/js/MultipleChoice/__test__/setAndGetValue.test.ts, src/js/MultipleChoice/index.ts, src/js/utils/AbstractMultiSelection.ts, src/react/Item/index.tsx, src/react/MultipleChoice/__test__/render.test.tsx, src/react/MultipleChoice/index.tsx
@youtr-s 
Please check and merge it.
I fixed the bug for KCB-986, KCB-998 and KCB-1001.
=> KUC unit test MultipleChoice bugfix

src/js/RadioButton/__test__/disableItem.test.ts, src/js/RadioButton/__test__/enable.test.ts, src/js/RadioButton/__test__/enableItem.test.ts, src/js/RadioButton/__test__/removeItem.test.ts, src/js/RadioButton/__test__/render.test.ts, src/js/RadioButton/index.ts, src/js/utils/AbstractSingleSelection.ts, src/react/RadioButton/__test__/render.test.tsx, src/react/RadioButton/index.tsx, src/react/utils/AbstractSingleSelection.tsx
=> KCB-1017, KCB-1008

docs/Reference/RadioButton.md
=> Mkdocs v0.7.0 ssr 639

.eslintignore, src/react/DateTime/__test__/onEvent.test.tsx, src/react/DateTime/index.tsx
=> SSR-806-fix-date-time

src/js/ColorPicker/index.ts
Fix picker can not show when change component from disable to enable
=> [Colorpicker] Fix picker can not show

README-JP.md, README.md
=> fix release note link

docs/0.1.5/mkdocs.yml, docs/0.2.0/mkdocs.yml, docs/0.3.0/mkdocs.yml, docs/0.3.1/mkdocs.yml, docs/0.3.2/mkdocs.yml, docs/0.3.3/mkdocs.yml, docs/0.3.4/mkdocs.yml, docs/0.3.5/mkdocs.yml, docs/0.3.6/mkdocs.yml, docs/0.3.8/mkdocs.yml, docs/0.4.0/mkdocs.yml, docs/0.4.1/mkdocs.yml, docs/0.4.2/mkdocs.yml, docs/0.4.3/mkdocs.yml, docs/0.4.5/mkdocs.yml, docs/0.5.0/mkdocs.yml, docs/0.6.0/mkdocs.yml, docs/0.7.0/mkdocs.yml, docs/0.7.1/mkdocs.yml, docs/0.7.2/mkdocs.yml, docs/0.7.3/mkdocs.yml, docs/0.7.4/mkdocs.yml, docs/0.7.5/mkdocs.yml, docs/0.7.6/mkdocs.yml, docs/mkdocs.yml
=> update google analytics link

src/radio-button/index.ts
fixed bug radio-button moved down on safari & component is full width on firefox
=> v1.0.4-SSR-1367 fixed bug radio-button moved down on safari

src/button/test/type.test.ts, src/mobile/button/test/type.test.ts, src/notification/test/type.test.ts
Button
MobileButton
Notification
=> v1.0.5_SSR-1666 Improve type prop unit test

src/button/test/text.test.ts, src/mobile/button/test/text.test.ts, src/mobile/notification/test/text.test.ts, src/notification/test/text.test.ts, src/spinner/test/text.test.ts
Button
MobileButton
Notification
MobileNotification
Spinner
=> v1.0.5_SSR-1669 Improve text prop unit test

src/button/test/render.test.ts, src/checkbox/test/render.test.ts, src/dialog/test/render.test.ts, src/dropdown/test/render.test.ts, src/mobile/button/test/render.test.ts, src/mobile/checkbox/test/render.test.ts, src/mobile/notification/test/render.test.ts, src/mobile/radio-button/test/render.test.ts, src/mobile/text/test/render.test.ts, src/mobile/textarea/test/render.test.ts, src/multichoice/test/render.test.ts, src/notification/test/render.test.ts, src/radio-button/test/render.test.ts, src/readonly-table/test/render.test.ts, src/spinner/test/render.test.ts, src/text/test/render.test.ts, src/textarea/test/render.test.ts
Reverts kintone-labs/kintone-ui-component#638
=> Revert "SSR-1685: Improve render test"

docs/document/docs/components/desktop/checkbox.md, docs/document/docs/components/desktop/dropdown.md, docs/document/docs/components/desktop/multichoice.md, docs/document/docs/components/desktop/radio-button.md, docs/document/docs/components/mobile/mobile-checkbox.md, docs/document/docs/components/mobile/mobile-radio-button.md, docs/document/website/translated_docs/ja/version-1.0.0/components/desktop/checkbox.md, docs/document/website/translated_docs/ja/version-1.0.0/components/desktop/dropdown.md, docs/document/website/translated_docs/ja/version-1.0.0/components/desktop/multichoice.md, docs/document/website/translated_docs/ja/version-1.0.0/components/desktop/radio-button.md, docs/document/website/translated_docs/ja/version-1.0.0/components/mobile/mobile-checkbox.md, docs/document/website/translated_docs/ja/version-1.0.0/components/mobile/mobile-radio-button.md, docs/document/website/versioned_docs/version-1.0.0/components/desktop/checkbox.md, docs/document/website/versioned_docs/version-1.0.0/components/desktop/dropdown.md, docs/document/website/versioned_docs/version-1.0.0/components/desktop/multichoice.md, docs/document/website/versioned_docs/version-1.0.0/components/desktop/radio-button.md, docs/document/website/versioned_docs/version-1.0.0/components/mobile/mobile-checkbox.md, docs/document/website/versioned_docs/version-1.0.0/components/mobile/mobile-radio-button.md
Dropdown, Checkbox, MobileCheckbox, RadioButton, MobileRadioButton, MultiChoice
=> v1.0.5_SSR-1673 Update value prop description

docs/document/docs/components/desktop/checkbox.md, docs/document/docs/components/desktop/multichoice.md, docs/document/docs/components/mobile/mobile-checkbox.md, docs/document/website/translated_docs/ja/version-1.0.0/components/desktop/checkbox.md, docs/document/website/translated_docs/ja/version-1.0.0/components/desktop/multichoice.md, docs/document/website/translated_docs/ja/version-1.0.0/components/mobile/mobile-checkbox.md, docs/document/website/versioned_docs/version-1.0.0/components/desktop/checkbox.md, docs/document/website/versioned_docs/version-1.0.0/components/desktop/multichoice.md, docs/document/website/versioned_docs/version-1.0.0/components/mobile/mobile-checkbox.md
update value default of Checkbox, MultiChoice, MobileCheckbox
=> v1.0.5 hotfix doc

demos/esm-dev-app/package-lock.json, package-lock.json
set-value and immer and nth-check
=> v1.1.1_SSR-1755 update some packages

src/dropdown/index.ts, src/multichoice/index.ts
=> v1.3.0_SSR-1757 Delete duplicate item multichoice

src/dropdown/index.ts, src/multichoice/index.ts, src/multichoice/test/changeEvent.test.ts
=> v1.3.0_SSR-1757 Fix review

src/base/datetime/time/index.ts, src/base/datetime/utils/index.ts, src/base/validator.ts, src/time-picker/index.ts
- handle invalid time value
- Convert time value
- Calculate listbox position
=> v1.3.0_SSR-1806 Handle invalid time & convert value

src/base/datetime/time/index.ts
=> v1.3.0_SSR-1806 Accessibility

src/base/datetime/calendar/header/dropdown/month/index.ts, src/base/datetime/listbox/index.ts
=> v1.3.0_SSR-1869 Update listbox for accessibility

src/checkbox/index.ts, src/checkbox/test/changeEvent.test.ts, src/dropdown/index.ts, src/dropdown/test/value.test.ts, src/mobile/checkbox/index.ts, src/mobile/checkbox/test/changeEvent.test.ts, src/mobile/checkbox/test/items.test.ts, src/mobile/checkbox/test/value.test.ts, src/mobile/dropdown/index.ts, src/mobile/dropdown/test/items.test.ts, src/mobile/dropdown/test/value.test.ts, src/mobile/multichoice/index.stories.js, src/mobile/multichoice/index.ts, src/mobile/radio-button/index.ts, src/mobile/radio-button/test/items.test.ts, src/mobile/radio-button/test/value.test.ts, src/multichoice/index.ts, src/radio-button/index.ts, src/radio-button/test/value.test.ts
- refactor dropdown & multichocie (delete code in constructor)
- implemenet for checkbox & radio-button
=> v1.3.0_SSR-1757 Delete duplicate for checkbox & radio-button

src/base/datetime/time/index.ts, src/time-picker/index.ts
- revert requiredIcon css
- issues at dev#9 SSR-1863
=> v1.3.0_SSR-1806_TimePicker fix issues 1863

src/base/datetime/date/index.ts, src/date-picker/index.ts
1. Fix bug click other component
2. revert css requiredIcon
=> v1.3.0_SSR-1807_DatePicker 

LICENSE
=> v1.3.0 SSR-1810 Delete lit-element and lit-html.

src/base/datetime/date/index.ts, src/date-picker/index.ts
=> v1.3.0_SSR-1807_DatePicker_fix_css

package-lock.json, package.json
karma
node-fetch
nanoid
log4js
=> v1.3.0_SSR-1810 upgrade packages

package-lock.json, package.json
=> update karma, engine.io, follow-redirects

.github/workflows/netlify_document_staging.yml, .github/workflows/netlify_storybook_staging.yml
=> v1.3.1_SSR-1966 deploy with netlify-cli

.github/dependabot.yml
=> master_SSR-1779 turn on the dependabot check

docs/document/docs/releases/release-notes.md, docs/document/website/translated_docs/ja/version-1.0.0/releases/release-notes-v1.3.2.md, docs/document/website/translated_docs/ja/version-1.3.2/releases/release-note.md, docs/document/website/versioned_docs/version-1.0.0/releases/release-notes-v1.3.2.md, docs/document/website/versioned_docs/version-1.3.2/releases/release-note.md
=> Fixed release notes

src/radio-button/index.ts, src/radio-button/test/error.test.ts, src/radio-button/test/label.test.ts, src/radio-button/test/requiredIcon.test.ts
Reverts kintone-labs/kintone-ui-component#973
=> Revert "v1.4.0-SSR-2078-Radio-button Apply base label / error"

CONTRIBUTING.md, README-JP.md, README.md
- Update roadmap link target
- Add Discussions link as our community
=> master_hotfix: update README

src/base/datetime/resource/constant.ts, src/datetime-picker/index.stories.js, src/datetime-picker/index.ts, src/datetime-picker/test/max.test.ts, src/datetime-picker/test/min.test.ts, src/datetime-picker/test/timeStep.test.ts, src/datetime-picker/test/value.test.ts, src/time-picker/index.ts
=> v1.4.0_SSR-2084 Add timeStep property on DateTimePicker

.github/workflows/execute_yamory_v0.yml
=> v0_dev hot-fix

docs/document/docs/components/mobile/mobile-time-picker.md, docs/document/website/sidebars.json, docs/document/website/static/css/custom.css, docs/document/website/static/js/samples/mobile-time-picker.js, docs/document/website/translated_docs/ja/version-1.4.0/components/mobile/mobile-time-picker.md, docs/document/website/versioned_docs/version-1.4.0/components/mobile/mobile-time-picker.md, docs/document/website/versioned_sidebars/version-1.4.0-sidebars.json
=> V1.4.0 ssr 2286 create mobile time picker document

docs/document/website/translated_docs/ja/version-1.4.0/components/mobile/mobile-time-picker.md
=> create JA MobileTimePicker document

docs/document/website/translated_docs/ja/version-1.4.0/components/mobile/mobile-date-picker.md
=> create JA MobileDatePicker document

scripts/webpack-esm.js, src/base/datetime/calendar/body/index.ts, src/base/datetime/calendar/body/style.ts, src/base/datetime/calendar/footer/index.ts, src/base/datetime/calendar/footer/style.ts, src/base/datetime/calendar/header/dropdown/month/index.ts, src/base/datetime/calendar/header/dropdown/month/style.ts, src/base/datetime/calendar/header/dropdown/year/index.ts, src/base/datetime/calendar/header/dropdown/year/style.ts, src/base/datetime/calendar/header/index.ts, src/base/datetime/calendar/header/style.ts, src/base/datetime/calendar/header/test/month.test.ts, src/base/datetime/calendar/header/test/year.test.ts, src/base/datetime/calendar/index.ts, src/base/datetime/calendar/style.ts, src/base/datetime/date/index.ts, src/base/datetime/date/style.ts, src/base/datetime/listbox/index.ts, src/base/datetime/listbox/style.ts, src/base/datetime/mobile-calendar/header/index.ts, src/base/datetime/mobile-time/index.ts, src/base/datetime/time/index.ts, src/date-picker/index.ts, src/date-picker/style.ts, src/date-picker/test/changeEvent.test.ts, src/date-picker/type.ts
=> v1.4.0_SSR-1845_DatePicker

scripts/webpack-esm.js, src/time-picker/index.ts, src/time-picker/style.ts, src/time-picker/test/accessibility.test.ts, src/time-picker/test/changeEvent.test.ts, src/time-picker/test/timeStep.test.ts, src/time-picker/type.ts
=> v1.4.0_SSR-1845_SSR-2378_TimePicker

scripts/webpack-esm.js, src/text/index.ts, src/text/style.ts, src/text/type.ts
=> v1.4.0_SSR-1845_SSR-2378_Text

README.md
+ Added info to the Installation section
+ Updated UMD sample code
=> v1.4.0_docs - SSR-2375 - Update README.md

docs/document/website/translated_docs/ja/version-1.4.0/components/desktop/button.md, docs/document/website/translated_docs/ja/version-1.4.0/components/desktop/checkbox.md, docs/document/website/translated_docs/ja/version-1.4.0/components/desktop/date-picker.md, docs/document/website/translated_docs/ja/version-1.4.0/components/desktop/datetime-picker.md, docs/document/website/translated_docs/ja/version-1.4.0/components/desktop/dialog.md, docs/document/website/translated_docs/ja/version-1.4.0/components/desktop/dropdown.md, docs/document/website/translated_docs/ja/version-1.4.0/components/desktop/multichoice.md, docs/document/website/translated_docs/ja/version-1.4.0/components/desktop/notification.md, docs/document/website/translated_docs/ja/version-1.4.0/components/desktop/radio-button.md, docs/document/website/translated_docs/ja/version-1.4.0/components/desktop/spinner.md, docs/document/website/translated_docs/ja/version-1.4.0/components/desktop/text.md, docs/document/website/translated_docs/ja/version-1.4.0/components/desktop/textarea.md, docs/document/website/translated_docs/ja/version-1.4.0/components/desktop/time-picker.md, docs/document/website/translated_docs/ja/version-1.4.0/components/mobile/mobile-button.md, docs/document/website/translated_docs/ja/version-1.4.0/components/mobile/mobile-checkbox.md, docs/document/website/translated_docs/ja/version-1.4.0/components/mobile/mobile-date-picker.md, docs/document/website/translated_docs/ja/version-1.4.0/components/mobile/mobile-datetime-picker.md, docs/document/website/translated_docs/ja/version-1.4.0/components/mobile/mobile-dropdown.md, docs/document/website/translated_docs/ja/version-1.4.0/components/mobile/mobile-multichoice.md, docs/document/website/translated_docs/ja/version-1.4.0/components/mobile/mobile-notification.md, docs/document/website/translated_docs/ja/version-1.4.0/components/mobile/mobile-radio-button.md, docs/document/website/translated_docs/ja/version-1.4.0/components/mobile/mobile-text.md, docs/document/website/translated_docs/ja/version-1.4.0/components/mobile/mobile-textarea.md, docs/document/website/translated_docs/ja/version-1.4.0/components/mobile/mobile-time-picker.md
+ Updated the sample code of all components under translated_docs/ja/version-1.4.0
=> V1.4.0_docs - SSR-2375 - Update All JP Components

.github/workflows/execute_yamory_v1.yml, .github/workflows/execute_yamory_weekly.yml, CONTRIBUTING.md, README-JP.md, README.md, docs/document/.gitignore
=> v1.4.0_SSR-2430 fix reverted files

README.md
=> v0_hotfix: add v0 maintenance stop possibility announcement

scripts/webpack-umd.js
=> v1.4.0_SSR-1845_implement accepting Kuc object

README.md
=> v1.4.0_SSR-2375 update version conflict description on README en

eslint-plugin-kuc-v1/no-sorting-in-alphabetical-order.js
=> v1.4.0_SSR-2454_check-js-error-in-es-lint-rule

src/button/style.ts
+ Fixed button style not returning to normal state after being clicked
+ Added focus outline when the button is in the hover or active state by keyboard
=> SSR-2483 - Unify Button style with Mantle

README-JP.md, README.md, docs/document/package-lock.json, docs/document/website/package-lock.json, licensefinder/doc/approval_devdependency_decisions.yml
=> upgrade package with node v16 && fix security alerts

tsconfig.esm.json, tsconfig.json, tsconfig.test.json, webpack.esm.config.js
=> SSR-1981 improve tsconfig

docs/document/docs/components/desktop/button.md, docs/document/docs/components/desktop/text.md, docs/document/docs/getting-started/custom-css.md, docs/document/website/translated_docs/ja/version-1.5.0/components/desktop/button.md, docs/document/website/translated_docs/ja/version-1.5.0/components/desktop/text.md, docs/document/website/translated_docs/ja/version-1.5.0/getting-started/custom-css.md, docs/document/website/versioned_docs/version-1.5.0/components/desktop/button.md, docs/document/website/versioned_docs/version-1.5.0/components/desktop/text.md, docs/document/website/versioned_docs/version-1.5.0/getting-started/custom-css.md
=> SSR-2360: Fix EN doc structure and Create JA Custom CSS doc

src/multichoice/style.ts, src/text/style.ts, src/textarea/style.ts
- Text
- TextArea
- Multichoice
=> SSR-2479 Fix excess height & text width

scripts/webpack-esm.js
=> SSR-2512 fix issue when build esm on Windows

scripts/webpack-umd.js
=> SSR-2599 improve webpack-umd.js to add pattern "\n"

src/button/index.stories.js, src/button/style.ts, src/dialog/style.ts
=> SSR-2569 change border style focus-visible

src/base/datetime/mobile-calendar/body/index.ts
=> hot-fix-mobile-datepicker-error

src/base/error/style.ts, src/base/label/style.ts, src/base/mobile-error/style.ts, src/base/mobile-label/style.ts, src/button/style.ts, src/checkbox/style.ts, src/dialog/style.ts, src/dropdown/style.ts, src/mobile/button/style.ts, src/mobile/checkbox/style.ts, src/mobile/dropdown/style.ts, src/mobile/multichoice/style.ts, src/mobile/notification/style.ts, src/mobile/radio-button/style.ts, src/mobile/text/style.ts, src/mobile/textarea/style.ts, src/multichoice/style.ts, src/notification/style.ts, src/radio-button/style.ts, src/spinner/style.ts, src/text/style.ts, src/textarea/style.ts
=> SSR-2275: Add Traditional Chinese for other components

src/date-picker/index.ts, src/mobile/date-picker/index.ts
=> SSR-2582 Disable popup calendar when clicking DatePicker and MobileDatePicker label part

src/mobile/checkbox/index.ts, src/textarea/index.ts
=> SSR-2632_Update aria-invalid for TextArea and MobileCheckbox

src/js/DateTime/index.ts
=> v0_SSR-2313_fix-calendar-not-close-issue-for-DateTime

.github/workflows/check_release_v0.yml, .github/workflows/commit_v0.yml
=> SSR-2695_upgrade ubuntu version to latest on CI

.github/workflows/check_release_v1.yml, .github/workflows/commit_v1.yml, .github/workflows/upload_release_v0.yml, .github/workflows/upload_release_v1.yml
=> SSR-2695_upgrade ubuntu version to latest on CI for v1

src/checkbox/index.ts, src/checkbox/type.ts, src/date-picker/index.ts, src/date-picker/type.ts, src/datetime-picker/index.ts, src/datetime-picker/type.ts, src/dropdown/index.ts, src/dropdown/type.ts, src/multichoice/index.ts, src/multichoice/type.ts, src/radio-button/index.ts, src/radio-button/type.ts, src/text/index.ts, src/text/type.ts, src/textarea/index.ts, src/textarea/type.ts, src/time-picker/index.ts, src/time-picker/type.ts
=> SSR-2729 exporting CustomEventDetail Desktop

demos/esm-dev-app/package-lock.json, docs/document/package-lock.json, package-lock.json, package.json
=> SSR-2609_upgrade-pakckages for EOLCheck_v1

src/button/style.ts
=> SSR-2670_fix Button CSS issue for each type

src/base/datetime/calendar/header/style.ts, src/base/datetime/listbox/style.ts
=> SSR-2656_Fix the year and month list font-weight of DatePicker and DateTimePicker

src/base/kuc-base.ts
=> SSR-2698 exporting CustomEventDetail base

demos/typescript-app/README.md, docs/document/website/translated_docs/ja/version-1.7.0/getting-started/usage-with-typescript.md
=> SSR-2728: update CustomEventDetail type part on ja doc and modify demo-app readme

src/datetime-picker/index.ts
=> SSR-2481_fix-maxStatements-eslint-warning-for-Datetime-Picker

src/base/datetime/calendar/header/test/accessibilibty.test.ts, src/base/datetime/calendar/header/test/highlight.test.ts, src/base/datetime/listbox/index.ts, src/time-picker/test/changeEvent.test.ts
=> SSR-2762_fix-calendar-listbox-sotrybook-warning

src/button/index.stories.js, src/checkbox/index.stories.js, src/dropdown/index.stories.js, src/mobile/button/index.stories.js, src/mobile/checkbox/index.stories.js, src/mobile/dropdown/index.stories.js, src/mobile/multichoice/index.stories.js, src/mobile/radio-button/index.stories.js, src/mobile/text/index.stories.js, src/mobile/textarea/index.stories.js, src/multichoice/index.stories.js, src/radio-button/index.stories.js, src/radio-button/index.ts, src/radio-button/type.ts, src/text/index.stories.js, src/textarea/index.stories.js
=> SSR-2628_update-storybook-coding-way

.github/dependabot.yml
=> Hot fix dependabot configuration

.github/dependabot.yml
=> Develop merge master

src/text/style.ts
=> SSR-2908_fix disabled css issue for Text in group field

src/button/style.ts, src/text/style.ts
=> SSR-2697 Fix custom width for Button and Text

docs/document/website/static/css/custom-kuc.css
=> SSR-2988 update Table ReadOnlyTable css document

src/attachment/style.ts
=> SSR-2993_Remove the gap between Attachment and it's Child Node

src/notification/style.ts
=> SSR-2992_fix notification display issue

.github/workflows/check_license_v1.yml, .github/workflows/check_release_v1.yml, .github/workflows/commit_v1.yml, .github/workflows/execute_yamory_v1.yml, .github/workflows/execute_yamory_weekly.yml, .github/workflows/netlify_document_live.yml, .github/workflows/netlify_document_staging.yml, .github/workflows/netlify_storybook_live.yml, .github/workflows/netlify_storybook_staging.yml, .github/workflows/upload_release_v0.yml, .github/workflows/upload_release_v1.yml
=> SSR-3020_v1_Change Actions Version to v3

.github/workflows/check_license_v0.yml, .github/workflows/check_release_v0.yml, .github/workflows/commit_v0.yml, .github/workflows/execute_yamory_v0.yml
=> SSR-3020_v0-dev Change Actions Version to v3

.github/workflows/check_release_v1.yml, .github/workflows/upload_release_v0.yml, .github/workflows/upload_release_v1.yml
=> SSR-3028 remove unnecessary comment on CI

docs/document/website/versioned_sidebars/version-1.9.0-sidebars.json
=> SSR-2795_Recovering time-picker for version-1.9.0-sidebars.json

src/dialog/style.ts, src/notification/style.ts
=> SSR-3045_fix icon and text position of dialog/notification

package.json
=> SSR-3025 update version to 1.9.0

LICENSE
- Delete unnecessary license info
- Add uuid license info
=> SSR-3025: update LICENSE file

src/readonly-table/index.ts
=> [hotfix] SSR-3025(v1): hotfix readonly-table display

src/mobile/multichoice/index.stories.js
=> SSR-3067(v1): Update the display of MobileMultiChoice in storybook

docs/document/website/translated_docs/ja/version-1.9.0/components/desktop/combobox.md
=> SSR-3025(v1): hotfix Combobox ja doc

package-lock.json, package.json
=> SSR-3027: investigate the way to enable actionlint locally

.github/workflows/netlify_document_staging.yml
=> SSR-2994: Update CI to check component preview on staging env of user guide

package.json
=> SSR-3137: Upgrade version to 1.10.0

docs/document/docs/components/desktop/dialog.md, docs/document/docs/components/desktop/tooltip.md, docs/document/i18n/ja/docusaurus-plugin-content-docs/current/components/desktop/dialog.md, docs/document/i18n/ja/docusaurus-plugin-content-docs/current/components/desktop/tooltip.md
=> SSR-3964: Update the user guide to improve search engine results
